$(document).ready(function () {
	
	$('#boton1').click(function(){
		$('*').css({background:'white'})
			alert("boton precionado")
    		$('.cuadrito:lt(8)').css({background:'red'})
    	})

	$('#boton2').click(function(){
		$('*').css({background:'white'})
    		alert("boton precionado")
    		$('.cuadrito:nth-of-type(8)').css({background:'red'})
			$('.cuadrito:nth-of-type(16)').css({background:'red'})
    		$('.cuadrito:nth-of-type(24)').css({background:'red'})
            $('.cuadrito:nth-of-type(32)').css({background:'red'})
            $('.cuadrito:nth-of-type(40)').css({background:'red'})
            $('.cuadrito:nth-of-type(48)').css({background:'red'})
            $('.cuadrito:nth-of-type(56)').css({background:'red'})
    		$('.cuadrito:last').css({background:'red'})
    	})


    $('#boton3').click(function(){
    	$('*').css({background:'white'})
    		alert("boton precionado")
    		$('.cuadrito:first').css({background:'red'})
    		$('.cuadrito:nth-of-type(9)').css({background:'red'})
    		$('.cuadrito:nth-of-type(17)').css({background:'red'})
    		$('.cuadrito:nth-of-type(25)').css({background:'red'})
            $('.cuadrito:nth-of-type(33)').css({background:'red'})
            $('.cuadrito:nth-of-type(41)').css({background:'red'})
            $('.cuadrito:nth-of-type(49)').css({background:'red'})
            $('.cuadrito:nth-of-type(57)').css({background:'red'})
    	})

    $('#boton4').click(function(){
    	$('*').css({background:'white'})
    		alert("boton precionado")
    		$('.cuadrito:gt(0):lt(6)').css({background:'red'})
    	})

    $('#boton5').click(function(){
    	$('*').css({background:'white'})
    		alert("boton precionado")
    		$('.cuadrito:nth-of-type(n+57)').css({background:'red'})
          })
    
    $('#boton6').click(function(){
    	$('*').css({background:'white'})
    		alert("boton precionado")
            $('.cuadrito:nth-of-type(n+57)').css({background:'red'})
    		$('.cuadrito:first').css({background:'red'})
            $('.cuadrito:lt(8)').css({background:'red'})
            $('.cuadrito:nth-of-type(9)').css({background:'red'})
            $('.cuadrito:nth-of-type(17)').css({background:'red'})
            $('.cuadrito:nth-of-type(25)').css({background:'red'})
            $('.cuadrito:nth-of-type(33)').css({background:'red'})
            $('.cuadrito:nth-of-type(41)').css({background:'red'})
            $('.cuadrito:nth-of-type(49)').css({background:'red'})
            $('.cuadrito:nth-of-type(57)').css({background:'red'})
            $('.cuadrito:nth-of-type(8)').css({background:'red'})
            $('.cuadrito:nth-of-type(16)').css({background:'red'})
            $('.cuadrito:nth-of-type(24)').css({background:'red'})
            $('.cuadrito:nth-of-type(32)').css({background:'red'})
            $('.cuadrito:nth-of-type(40)').css({background:'red'})
            $('.cuadrito:nth-of-type(48)').css({background:'red'})
            $('.cuadrito:nth-of-type(56)').css({background:'red'})
            $('.cuadrito:last').css({background:'red'})

    	})
	
	$('#boton7').click(function(){
		$('*').css({background:'white'})
    		alert("boton precionado")
    		$('.cuadrito:lt(8)').css({background:'red'})
            $('.cuadrito:nth-of-type(9)').css({background:'red'})
            $('.cuadrito:nth-of-type(17)').css({background:'red'})
            $('.cuadrito:nth-of-type(25)').css({background:'red'})
            $('.cuadrito:nth-of-type(33)').css({background:'red'})
            $('.cuadrito:nth-of-type(41)').css({background:'red'})
            $('.cuadrito:nth-of-type(49)').css({background:'red'})
            $('.cuadrito:nth-of-type(57)').css({background:'red'})
            $('.cuadrito:nth-of-type(15)').css({background:'red'})
            $('.cuadrito:nth-of-type(22)').css({background:'red'})
            $('.cuadrito:nth-of-type(29)').css({background:'red'})
            $('.cuadrito:nth-of-type(36)').css({background:'red'})
            $('.cuadrito:nth-of-type(43)').css({background:'red'})
            $('.cuadrito:nth-of-type(50)').css({background:'red'})
            
              
    	})
    
    $('#boton8').click(function(){
    	$('*').css({background:'white'})
    		alert("boton precionado")
    		$('.cuadrito:first').css({background:'red'})
            $('.cuadrito:last').css({background:'red'})
    		$('.cuadrito:nth-of-type(15)').css({background:'red'})
            $('.cuadrito:nth-of-type(22)').css({background:'red'})
            $('.cuadrito:nth-of-type(29)').css({background:'red'})
            $('.cuadrito:nth-of-type(36)').css({background:'red'})
            $('.cuadrito:nth-of-type(43)').css({background:'red'})
            $('.cuadrito:nth-of-type(10)').css({background:'red'})
            $('.cuadrito:nth-of-type(19)').css({background:'red'})
            $('.cuadrito:nth-of-type(28)').css({background:'red'})
            $('.cuadrito:nth-of-type(37)').css({background:'red'})
            $('.cuadrito:nth-of-type(46)').css({background:'red'})
            $('.cuadrito:nth-of-type(50)').css({background:'red'})
            $('.cuadrito:nth-of-type(55)').css({background:'red'})
            $('.cuadrito:nth-of-type(57)').css({background:'red'})  
            $('.cuadrito:nth-of-type(8)').css({background:'red'})  
    	})
    
    $('#boton9').click(function(){
    	$('*').css({background:'white'})
    		alert("boton precionado")
    	  	$('.cuadrito:gt(2):lt(2)').css({background:'red'})
    		$('.cuadrito:gt(10):lt(2)').css({background:'red'})
    		$('.cuadrito:gt(18):lt(2)').css({background:'red'})
    		$('.cuadrito:gt(23):lt(8)').css({background:'red'})
            $('.cuadrito:gt(31):lt(8)').css({background:'red'})
            $('.cuadrito:gt(42):lt(2)').css({background:'red'})
            $('.cuadrito:gt(50):lt(2)').css({background:'red'})
            $('.cuadrito:gt(58):lt(2)').css({background:'red'})
    	})
    
    $('#boton10').click(function(){
    	$('*').css({background:'white'})
    		alert("boton precionado")
            $('.cuadrito:nth-of-type(n+57)').css({background:'red'})
            $('.cuadrito:lt(8)').css({background:'red'})
            $('.cuadrito:nth-of-type(15)').css({background:'red'})
            $('.cuadrito:nth-of-type(22)').css({background:'red'})
            $('.cuadrito:nth-of-type(29)').css({background:'red'})
            $('.cuadrito:nth-of-type(36)').css({background:'red'})
            $('.cuadrito:nth-of-type(43)').css({background:'red'})
            $('.cuadrito:nth-of-type(50)').css({background:'red'})

    	})
    
    $('#boton11').click(function(){
    	$('*').css({background:'white'})
    		alert("boton precionado")
            $('.cuadrito:nth-of-type(n+57)').css({background:'red'})
            $('.cuadrito:first').css({background:'red'})
            $('.cuadrito:lt(8)').css({background:'red'})
            $('.cuadrito:nth-of-type(9)').css({background:'red'})
            $('.cuadrito:nth-of-type(17)').css({background:'red'})
            $('.cuadrito:nth-of-type(25)').css({background:'red'})
            $('.cuadrito:nth-of-type(33)').css({background:'red'})
            $('.cuadrito:nth-of-type(41)').css({background:'red'})
            $('.cuadrito:nth-of-type(49)').css({background:'red'})
            $('.cuadrito:nth-of-type(57)').css({background:'red'})
            $('.cuadrito:nth-of-type(8)').css({background:'red'})
            $('.cuadrito:nth-of-type(16)').css({background:'red'})
            $('.cuadrito:nth-of-type(24)').css({background:'red'})
            $('.cuadrito:nth-of-type(32)').css({background:'red'})
            $('.cuadrito:nth-of-type(40)').css({background:'red'})
            $('.cuadrito:nth-of-type(48)').css({background:'red'})
            $('.cuadrito:nth-of-type(56)').css({background:'red'})
            $('.cuadrito:last').css({background:'red'})    	
            $('.cuadrito:nth-of-type(15)').css({background:'red'})
            $('.cuadrito:nth-of-type(22)').css({background:'red'})
            $('.cuadrito:nth-of-type(29)').css({background:'red'})
            $('.cuadrito:nth-of-type(36)').css({background:'red'})
            $('.cuadrito:nth-of-type(43)').css({background:'red'})
            $('.cuadrito:nth-of-type(10)').css({background:'red'})
            $('.cuadrito:nth-of-type(19)').css({background:'red'})
            $('.cuadrito:nth-of-type(28)').css({background:'red'})
            $('.cuadrito:nth-of-type(37)').css({background:'red'})
            $('.cuadrito:nth-of-type(46)').css({background:'red'})
            $('.cuadrito:nth-of-type(50)').css({background:'red'})
            $('.cuadrito:nth-of-type(55)').css({background:'red'})
            $('.cuadrito:nth-of-type(57)').css({background:'red'})
        })
    
    $('#boton12').click(function(){
    	$('*').css({background:'white'})
    		alert("boton precionado")
    	})


})
